### ISSUE TITLE
Plugin usage in Netbeans

### ISSUE THREAD

**Issue by Edijae** [nb-ldap-explorer/nb-ldap-explorer#4]
How do i use SSL Certificate Exception in netbeans 8.2? I installed it but don't how to access it.

**Comment by matthiasblaesing** [comment]
SSL Certificate Exception hooks into the verification process. Access a site, with a an invalid certificate, and you will get a popup with the request whether or not you want to accept the invalid certificate.

**Comment by Edijae** [comment]
@matthiasblaesing  I'm consuming a webservice in java and making a soap request. it worked well in google app engine sometimes back but now I'm trying to test in on netbeans. The error that was thrown was 
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching [website name] found. I've tried adding the website in java cert file and truststore in Ubuntu but it didn't work

**Comment by matthiasblaesing** [comment]
You did not say on which java version you are running. Anything newer than java 8 might be problematic (jaxb was removed from the default) modules. What is more, the soap stack might not use the default truststore and this circumvent the certificate exception code. Depending on the soap bindings you are using it might be worth to look for binding specific solutions.

**Comment by Edijae** [comment]
I'm using java 8. I've contacted the company that i was trying to consume it's webservice and informed me they have already decommissioned it in favor of a restful api which is easy to implement. I've thus abandoned their webservice since it can't work. 

Thank you very much for the help @matthiasblaesing
