### ISSUE TITLE
Merge LDAP Explorer with LDIF Editor

### ISSUE THREAD

**Issue by jkovalsky** [nb-ldap-explorer/nb-ldap-explorer#7]
I would like to ask about the LDIF Editor plugin for Apache NetBeans. Why isn't it bundled in LDAP Explorer plugin if it only makes sense with it? Would it make sense to merge the two into one Apache NetBeans plugin?

**Comment by matthiasblaesing** [comment]
As is the case with many things in IT, it has evolved organically. Historically there were three plugins:

- LDAP Explorer, the component to access LDAP
- LDIF Editor, the component that shows LDIF data
- SSL Certificate Exception, the component that allowed users to defined exceptions where TLS certificates were "less correctly" installed

Given that the third component needs to be rebuild (the integration does not work anymore), I might indeed fold all components into one big plugin.

**Comment by matthiasblaesing** [comment]
@jkovalsky thanks for bringing the idea up. I just released 0.19, which integrates the functions into the main module.
